@extends('layouts.government')
@section('title', 'Dashboard Monitoring Karhutla | SIGMA')
@section('content')
@php($data = config('sigma_data'))
<section class="page-heading"><div><p class="breadcrumb">Beranda › Dashboard</p><h1>Dashboard Monitoring Karhutla</h1><p>Pantauan kondisi karhutla nasional secara realtime.</p></div><span class="system-status">● Data diperbarui 2 menit lalu</span></section>
<div class="stats-grid">@foreach($data['government_metrics'] as $metric)<x-sigma.stat-card :label="$metric['label']" :value="$metric['value']" :icon="$metric['icon']" :accent="$metric['accent']" caption="<b class='success'>↑ Data realtime</b>"/>@endforeach</div>
<div class="government-grid"><section class="panel"><div class="panel-title"><div><h3>Peta Monitoring</h3><p>Hotspot, zona risiko, dan area kejadian</p></div><button class="button button-light" data-toast="Layer peta diperbarui">⌖ Layer Peta</button></div><div class="map-placeholder monitoring-map"><div class="map-controls">＋<hr>−</div><div class="island island-one"></div><div class="island island-two"><i></i><i></i></div><div class="island island-three"></div><div class="island island-four"></div><div class="map-legend"><span class="danger">● Hotspot</span><span class="orange-text">● Zona Risiko</span><span class="warning">● Area Kejadian</span><span>□ Batas Wilayah</span></div></div></section><section class="panel activity-panel"><h3>Aktivitas Terbaru</h3>@foreach($data['recent_activities'] as $activity)<div class="gov-activity"><time>{{ $activity['time'] }}</time><i class="{{ $activity['type'] }}">●</i><b>{{ $activity['label'] }}</b></div>@endforeach)<button class="button button-light" data-modal="activity-modal">Lihat Semua Aktivitas</button></section></div>
<x-sigma.modal id="activity-modal" title="Aktivitas Terkini"><p>Sinkronisasi data satelit berhasil dan seluruh indikator risiko telah diperbarui.</p><div class="modal-actions"><button class="button button-primary" data-modal-close>Tutup</button></div></x-sigma.modal>
@endsection
