import 'package:flutter/material.dart';
const sigmaRed = Color(0xFFC82828), sigmaNavy = Color(0xFF172033), sigmaPale = Color(0xFFF6F8FC), sigmaBlue = Color(0xFFE8F0FF), sigmaGreen = Color(0xFF078443), sigmaOrange = Color(0xFFF97316);

class SigmaCard extends StatelessWidget { const SigmaCard({super.key, required this.child, this.padding = const EdgeInsets.all(16), this.color = Colors.white}); final Widget child; final EdgeInsets padding; final Color color; @override Widget build(BuildContext c) => Container(padding: padding, decoration: BoxDecoration(color: color, borderRadius: BorderRadius.circular(16), boxShadow: const [BoxShadow(color: Color(0x10172033), blurRadius: 12, offset: Offset(0,4))]), child: child); }
class SigmaChip extends StatelessWidget { const SigmaChip({super.key, required this.text, this.color = sigmaGreen}); final String text; final Color color; @override Widget build(BuildContext c) => Container(padding: const EdgeInsets.symmetric(horizontal: 10,vertical: 5), decoration: BoxDecoration(color: color.withValues(alpha: .13),borderRadius: BorderRadius.circular(20)), child: Text(text, style: TextStyle(fontSize: 11,fontWeight: FontWeight.w800,color: color))); }
class SigmaButton extends StatelessWidget { const SigmaButton({super.key, required this.label, required this.onPressed, this.icon, this.secondary = false, this.color}); final String label; final VoidCallback onPressed; final IconData? icon; final bool secondary; final Color? color; @override Widget build(BuildContext c) => SizedBox(height: 52, child: FilledButton.icon(onPressed:onPressed, icon: icon == null ? const SizedBox.shrink() : Icon(icon), label:Text(label), style:FilledButton.styleFrom(backgroundColor: secondary ? sigmaBlue : color ?? sigmaRed, foregroundColor: secondary ? sigmaNavy : Colors.white, shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(10)), textStyle:const TextStyle(fontWeight:FontWeight.w800)))); }
class SigmaHeader extends StatelessWidget { const SigmaHeader({super.key, required this.title, this.subtitle, this.back = false, this.onBack, this.online = true}); final String title; final String? subtitle; final bool back, online; final VoidCallback? onBack; @override Widget build(BuildContext c) => Row(children:[if(back) IconButton(onPressed:onBack ?? ()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back)) else ClipRRect(borderRadius:BorderRadius.circular(9),child:Image.asset('assets/images/logo.jpeg',width:39,height:39,fit:BoxFit.cover)), const SizedBox(width:10), Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(back ? title : 'SIGMA',style:TextStyle(fontWeight:FontWeight.w900,fontSize: back?20:14,color:back?sigmaNavy:sigmaRed)),Text(back ? subtitle ?? '' : title,style:TextStyle(fontWeight:FontWeight.w800,fontSize:back?12:20,color:sigmaNavy))])), SigmaChip(text:online?'● ONLINE':'● OFFLINE',color:online?sigmaGreen:sigmaOrange), const SizedBox(width:8), if(!back) const CircleAvatar(radius:18,backgroundColor:sigmaRed,foregroundColor:Colors.white,child:Icon(Icons.person_outline))]); }
class Metric extends StatelessWidget { const Metric({super.key,required this.label,required this.value,required this.icon, this.color=sigmaRed}); final String label,value; final IconData icon; final Color color; @override Widget build(BuildContext c) => Expanded(child:Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:sigmaBlue,borderRadius:BorderRadius.circular(11)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:color,size:18),const SizedBox(height:7),Text(label,style:const TextStyle(fontSize:11)),Text(value,style:TextStyle(fontSize:18,fontWeight:FontWeight.w800,color:color))]))); }
class MockMap extends StatelessWidget { const MockMap({super.key, this.height = 250, this.route = false, this.onTap}); final double height; final bool route; final VoidCallback? onTap; @override Widget build(BuildContext c)=>InkWell(onTap:onTap,child:Container(height:height,decoration:BoxDecoration(color:const Color(0xFFD9F5E4),borderRadius:BorderRadius.circular(16)),child:Stack(children:[Positioned.fill(child:CustomPaint(painter:_MapPainter(route))), const Positioned(top:14,left:14,child:SigmaChip(text:'GPS Akurat ±3m')), Positioned(right:24,top:70,child:CircleAvatar(backgroundColor:sigmaRed,foregroundColor:Colors.white,child:Icon(Icons.local_fire_department))), Positioned(left:45,bottom:35,child:CircleAvatar(backgroundColor:sigmaGreen,foregroundColor:Colors.white,child:Icon(Icons.person_pin_circle))), const Positioned(right:12,bottom:12,child:Column(children:[CircleAvatar(child:Icon(Icons.add)),SizedBox(height:6),CircleAvatar(child:Icon(Icons.remove))]))]))); }
class _MapPainter extends CustomPainter { const _MapPainter(this.route); final bool route; @override void paint(Canvas c,Size s){final p=Paint()..color=const Color(0x8860A5FA)..strokeWidth=5..style=PaintingStyle.stroke; c.drawLine(Offset(0,s.height*.7),Offset(s.width,s.height*.35),p); if(route){p..color=sigmaOrange..strokeWidth=7; final path=Path()..moveTo(s.width*.2,s.height*.85)..lineTo(s.width*.48,s.height*.55)..lineTo(s.width*.74,s.height*.2); c.drawPath(path,p);} else {p..color=const Color(0xAAE54646)..strokeWidth=4; c.drawCircle(Offset(s.width*.67,s.height*.35),42,p);}} @override bool shouldRepaint(_MapPainter old)=>old.route!=route; }
